# Generated by Django 6.0.6 on 2026-06-17 09:43

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('georivasources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMIP6DataFeed',
            fields=[
                ('datafeed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='georivasources.datafeed')),
                ('country', django_countries.fields.CountryField(blank=True, help_text='Country to subset to. Its bounding box is resolved automatically via django-countries-geoextent. Leave blank to use a custom bounding box below, or neither for the full global domain.', max_length=2)),
                ('north', models.FloatField(blank=True, help_text='North latitude (custom bbox; overrides country).', null=True)),
                ('south', models.FloatField(blank=True, help_text='South latitude (custom bbox; overrides country).', null=True)),
                ('west', models.FloatField(blank=True, help_text='West longitude (custom bbox; overrides country).', null=True)),
                ('east', models.FloatField(blank=True, help_text='East longitude (custom bbox; overrides country).', null=True)),
                ('bias_adjustment', models.CharField(choices=[('none', 'None (raw)'), ('ls', 'Linear scaling'), ('isimip', 'ISIMIP method')], default='none', help_text="Bias-adjustment variant. 'None' (raw) is recommended and supported by all variables.", max_length=10)),
            ],
            options={
                'verbose_name': 'CMIP6 Data Feed',
            },
            bases=('georivasources.datafeed', models.Model),
        ),
        migrations.CreateModel(
            name='CMIP6DataFeedCollectionLink',
            fields=[
                ('datafeedcollectionlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='georivasources.datafeedcollectionlink')),
                ('experiment', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'CMIP6 Collection Link',
            },
            bases=('georivasources.datafeedcollectionlink',),
        ),
    ]
